### ISSUE TITLE
Could not download syns data

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#294]
![2016-11-25 01 33 05](https://cloud.githubusercontent.com/assets/20598279/20610757/54f27ec2-b2af-11e6-9da9-9c474b91f6ca.png)
![2016-11-25 01 35 15](https://cloud.githubusercontent.com/assets/20598279/20610788/e825ec1a-b2af-11e6-8e0c-c58dc176f0e4.png)

![2016-11-25 01 36 25](https://cloud.githubusercontent.com/assets/20598279/20610780/b4c6f2ec-b2af-11e6-9684-1f52d2a2d135.png)
![2016-11-25 01 36 36](https://cloud.githubusercontent.com/assets/20598279/20610782/bfe3eaa4-b2af-11e6-92fc-3db3407415b8.png)

All actions on one server. Please help

**Comment by Daniil145** [comment]
npm test:
```
 npm test

> farmbot-mqtt-gateway@1.1.0 test /root/mqtt-gateway
> istanbul cover node_modules/.bin/jasmine

You did not set WEB_API_URL. Defaulting to http://localhost:3000
Started
Downloaded certificate from http://localhost:3000/api/public_key

        We test the MQTT server against a real running API instance on localhost:3000.
        Something went wrong while testing.
        Usually, this means you are not running a server.

Will fetch certificate...
Did fetch certifiacte. Will verify token with certificate.
FWill fetch certificate...
.Did fetch certifiacte. Will verify token with certificate.
STAND UP AN API SERVER LOCALLY!
AUTH START
AUTH FAIL admin@admin.com
Login credentials are too short. Use a JSON web token as password
[Error: Login credentials are too short. Use a JSON web token as password]
FAUTH START
AUTH FAIL admin@admin.com
Login credentials are too short. Use a JSON web token as password
[Error: Login credentials are too short. Use a JSON web token as password]
FAUTH START
AUTH FAIL admin@admin.com
Login credentials are too short. Use a JSON web token as password
[Error: Login credentials are too short. Use a JSON web token as password]
FFF

Failures:
1) token verification knows when you're telling the truth
  Message:
    Failed: Failed to validate JWT. Error is above.
  Stack:
    Error: Failed: Failed to validate JWT. Error is above.
        at failure (/root/mqtt-gateway/spec/security/verify_token_spec.js:9:2128)
        at process._tickCallback (node.js:377:9)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

2) authentication logs in with a JWT as a password
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at callback (/root/mqtt-gateway/spec/security/authenticate_spec.js:9:2226)
        at /root/mqtt-gateway/app/security/authenticate.js:9:2215
        at runMicrotasksCallback (node.js:335:7)
        at doNTCallback0 (node.js:428:9)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

3) authentication logs in with a username/password
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at callback (/root/mqtt-gateway/spec/security/authenticate_spec.js:9:2957)
        at /root/mqtt-gateway/app/security/authenticate.js:9:2215
        at runMicrotasksCallback (node.js:335:7)
        at doNTCallback0 (node.js:428:9)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

4) authentication logs in and attaches JSON web token to user
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at callback (/root/mqtt-gateway/spec/security/authenticate_spec.js:9:1508)
        at /root/mqtt-gateway/app/security/authenticate.js:9:2215
        at runMicrotasksCallback (node.js:335:7)
        at doNTCallback0 (node.js:428:9)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

5) token fetcher handles failure
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

6) token fetcher grabs a token off the API
  Message:
    Failed: Expected success response from server while testing token auth.
  Stack:
    Error: Failed: Expected success response from server while testing token auth.
        at no (/root/mqtt-gateway/spec/security/fetch_token_spec.js:9:1087)
        at runMicrotasksCallback (node.js:335:7)
        at doNTCallback0 (node.js:428:9)
        at process._tickCallback (node.js:357:13)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

7 specs, 6 failures
Finished in 35.445 seconds

Randomized with seed 81814
=============================================================================
Writing coverage object [/root/mqtt-gateway/coverage/coverage.json]
Writing coverage reports at [/root/mqtt-gateway/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 77.02% ( 124/161 )
Branches     : 60% ( 9/15 )
Functions    : 79.49% ( 31/39 )
Lines        : 77.02% ( 124/161 )
================================================================================
npm ERR! Test failed.  See above for more details.

```

**Comment by RickCarlino** [comment]
@Daniil145 Thanks for bringing these issues to our attention. In the future, please don't post multiple issues in a single thread. We follow the rule of "one issue per thread" to help others who are searching for answers to the same question.

As for the error you see when syncing, can I see what your Javascript console looks like? (ctrl + shift + J).

**Other things to note:**

**The `npm test` issue**: This will not affect your ability to run the software. If your goal is to contribute new features to the software, let's discuss the problem in a separate thread. Otherwise, you can safely ignore those errors and continue running the software.

**The `languages/ru.js` issue**: You're seeing this one because we don't have support for the Russian language yet :frowning_face:. If you wish to help write a Russian translation for the application, it would be greatly appreciated. We use [i18next](http://i18next.com/). You would need to add a `ru.js` file to the project. Please raise a separate issue if you require assistance in writing language files.

**Comment by Daniil145** [comment]
big thx,  I forgot change options application.rb 
```
ails.application.routes.default_url_options[:host] = ENV["API_HOST"] || "95.31.1.59" 
    Rails.application.routes.default_url_options[:port] = ENV["API_PORT"] || 80
```
and open ports for mqtt)

**Comment by RickCarlino** [comment]
@Daniil145 Great!
